version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing HashiCorp Packer..."
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.9.1/packer_1.9.1_linux_amd64.zip && unzip packer.zip -d ./bin/
      - echo "Installing jq..."
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - echo "Validating packer script"
      - ./bin/packer validate ./aws-ubuntu.pkr.hcl
  build:
    commands:
      ### HashiCorp Packer cannot currently obtain the AWS CodeBuild-assigned role and its credentials
      ### Manually capture and configure the AWS CLI to provide HashiCorp Packer with AWS credentials
      ### More info here: https://github.com/mitchellh/packer/issues/4279
      # - echo "Configuring AWS credentials"
      # - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      # - cat aws_credentials.json
      # - aws configure set region $AWS_REGION
      # - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
      # - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
      # - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
      - echo "Building Packer image"
      - ./bin/packer build ./aws-ubuntu.pkr.hcl
  post_build:
    commands:
      - echo "HashiCorp Packer build completed on `date`"