---
- set_fact:
    db_encode_map:
      jira:
        encoding: UNICODE
        lc_collate: C
        lc_ctype: C
      confluence:
        encoding: UTF8
        lc_collate: en_US.UTF-8
        lc_ctype: en_US.UTF-8
      default:
        encoding: UTF8
        lc_collate: en_US.UTF-8
        lc_ctype: en_US.UTF-8

- set_fact:
    db_encode: "{{ db_encode_map[appname]|default(db_encode_map['default']) }}"

- name: make sure RDS ready
  wait_for:
    host: "{{ my_db['host'] }}"
    port: "{{ my_db['port']|default('3306') }}"
    connect_timeout: 5
    sleep: 10
    timeout: 900
    state: started
  run_once: true

- name: install pip module for mysql
  pip:
    name: PyMySQL

- name: mysql - create database for {{ appname }}
  mysql_db:
    name: "{{ my_db['db'] }}"
    encoding: "{{ db_encode.encoding }}"
    login_user: "{{ my_db['admin_user'] }}"
    login_password: "{{ my_db['admin_passwd'] }}"
    login_host: "{{ my_db['host'] }}"
    login_port: "{{ my_db['port']|default('3306') }}"
    state: present
  register: create_db
  when: my_db['config']|default(true)
  run_once: true
  no_log: "{{ hide_sensitive_log|default(true) }}"

- name: mysql - create user for {{ appname }}
  mysql_user:
    name: "{{ my_db['user'] }}"
    password: "{{ my_db['passwd'] }}"
    update_password: on_create
    priv: "{{ my_db['db'] }}.*:ALL"
    append_privs: true
    host: "%"
    state: present
    login_user: "{{ my_db['admin_user'] }}"
    login_password: "{{ my_db['admin_passwd'] }}"
    login_host: "{{ my_db['host'] }}"
    login_port: "{{ my_db['port']|default('3306') }}"
  when: create_db.changed
  run_once: true
  no_log: "{{ hide_sensitive_log|default(true) }}"

#EazyBI
- name: mysql - create database for eazybi
  mysql_db:
    name: "{{ my_db['eazybi_db'] }}"
    encoding: "{{ db_encode.encoding }}"
    login_user: "{{ my_db['admin_user'] }}"
    login_password: "{{ my_db['admin_passwd'] }}"
    login_host: "{{ my_db['host'] }}"
    login_port: "{{ my_db['port']|default('3306') }}"
    state: present
  register: create_eazybi_db
  when: my_db['config']|default(true)
  run_once: true
  no_log: "{{ hide_sensitive_log|default(true) }}"

- name: mysql - create user for eazybi
  mysql_user:
    name: "{{ my_db['eazybi_user'] }}"
    password: "{{ my_db['eazybi_passwd'] }}"
    update_password: on_create
    priv: "{{ my_db['eazybi_db'] }}.*:ALL"
    append_privs: true
    host: "%"
    state: present
    login_user: "{{ my_db['admin_user'] }}"
    login_password: "{{ my_db['admin_passwd'] }}"
    login_host: "{{ my_db['host'] }}"
    login_port: "{{ my_db['port']|default('3306') }}"
  when: create_eazybi_db.changed
  run_once: true
  no_log: "{{ hide_sensitive_log|default(true) }}"
